### ISSUE TITLE
File sharing not working

### ISSUE THREAD

**Issue by gerner** [kn6plv/meshchat#18]
on version 2.8, when I upload a file, it only shows up on the local node. Remote nodes never see the file.

I believe this is a simple bug here:

https://github.com/kn6plv/meshchat/blob/master/src/data/www/cgi-bin/meshchat#L355

You're missing a tab between `stat.mtime` and `platform`. If I hack that tab in, things work all of a sudden.

I'll probably try and put together a PR for that soon.

**Comment by hickey** [comment]
Makes sense. Looking at the K7FPV code (original MeshChat) there was a tab between the two fields. So looks like an oversight when the code was re-written in LUA. 

Good find.

**Comment by gerner** [comment]
I just made a pull request for this: https://github.com/kn6plv/meshchat/pull/19

I made the same change on an AREDN node in an adhoc way and verified it works, but I'm not sure how to repackage meshchat for manual testing (I guess it's probably just `./build` ?) or if there's a test suite.

**Comment by ab7pa** [comment]
@gerner Nick, yes you should be able to run the `build` script and it will regenerate the packages.  Before you do that, though, you should increment the VERSION number inside the `build` script (probably 2.9 now).  Then include all of the changes in your PR.

**Comment by hickey** [comment]
I actually have the GitHub Actions workflow working correctly and building fully installable packages in my [reorg branch](https://github.com/hickey/meshchat/tree/reorg) (opened as #15). Releases occur automatically with just tagging the repo. 

Everything sort of came to a standstill weeks ago because I had to travel back out to Seattle to pack up the rest of my things and get the house on the market. I have been back for about 2 weeks and have been meaning to look at the branch and tidy up any loose ends. I can certainly make some time in the next couple of days to get that done so that a proper code review can be done on the branch.
