### ISSUE TITLE
Home needed for MeshChat

### ISSUE THREAD

**Issue by ab7pa** [kn6plv/meshchat#25]
@csadams and @hickey -- I'm sure you know that MeshChat is a third party app and **_not_** an AREDN app.  The AREDN development team has no decision-making involvement or control over MeshChat.  It was originally created in Perl by K7FPV in 2015, but he was no longer able to support it by around 2018.  It's a very clever, popular, and widely used application among AREDN groups -- but it does have its limitations.

A year or so ago when the Perl packages were retired from AREDN firmware, KN6PLV ported MeshChat to Lua so it could run on newer firmware without Perl.  However, Tim provided this as a temporary workaround because the app was so popular.  I don't think Tim has the time or inclination to continue developing MeshChat long term, so his repo will probably remain _status quo_.

**MeshChat needs a new home and a committed champion.**. Would either of you be willing to step in?  @hickey has a major rearchitecture in his own repo, and that might serve as a good foundation for moving forward.  If you are willing, then you could use your MeshChat repo as the basis for its future as a mesh application.

**Comment by csadams** [comment]
Hi Steve, thanks for the additional background... Tim had told me some of
that in our conversations.

I wish I could offer to take this on, since it seems like a nice manageable
size project with a good level of impact to AREDN users around the world.
Unfortunately I'm not a programmer and have never worked with Lua (hadn't
heard of it till recently), and my very limited and out-dated programming
skills would likely require LOTS of hand-holding.

That said, if Gerald @hickey is willing to take on the programming side, I
would be happy to help with product management and documentation
tasks, which are more my skill set.
Happy to discuss more if there's interest.

**Comment by hickey** [comment]
Funny that this has come up. I was thinking something along these lines last night or early this morning. 

A few months ago in #14 when @aanon4 stated that MeshChat was getting very little love I started preparing to be a maintainer of the project. But then I had to go back to Seattle for many weeks to finish packing up my house and get it sold off. Well that concluded yesterday and I have been back for a bit. My time is now becoming available where I can dedicate time to MeshChat again. 

I would be happy to become the maintainer of MeshChat and would welcome assistance from anyone including @csadams. There are certainly a host of things that will need to be done that don't include writing LUA code. Documentation is a big one right now, also getting a proper release process in place, and I am sure that there will be several more pop up in the coming months. 

Related to where the project/repo lives, the recent thoughts I had were that it gets moved to the AREDN organization here on GitHub. I know that many may take this as implicit support of MeshChat by the AREDN community, but the project would need to have a disclaimer that it is not an officially sanctioned project of AREDN. 

This could also open the door for other projects to find a home in the AREDN organization. I am not sure if that is good or bad. I am not on the AREDN project team and don't have insight into the philosophy that drives the AREDN project or the opinions of ancillary projects. 

A couple of the positives that I see is a location for making finding packages related to AREDN easier and getting more visibility for the ancillary projects. The negative aspect might be that a badly maintained project may cast a shadow on the AREDN project. If the AREDN project team supported the idea--great--but if there was not support for it I would certainly understand and support their position. 

Another thought I had as I was writing this was to create a new GitHub organization such as "AREDN Applications" or "AREDN Services" where the ancillary projects could live. 

I know that this could take some time to sort out and make a decision on the path forward. In the mean time I am happy to make my fork the primary development location and continue moving forward. If it is preferable, I can move my fork of MeshChat to another name and the project can be transferred to me so that all the issues, PRs and project collateral gets transferred too. I would hate to loose some of the issue discussions that have been going on.

**Comment by hickey** [comment]
@ab7pa @aanon4 is there interest in transferring the MeshChat project so that the issues and issue history can be preserved? 

Another reason I would prefer to have it transferred is so that there is not yet another repo of MeshChat out there providing confusion as to which is the active one. Once things settle down I will go re-write some of the MeshChat service page in the AREDN docs so that it is clearer what the current state of the different versions of MeshChat are and where to get support.

**Comment by aanon4** [comment]
Transfer - no. I didnt take over the original Perl repo either.

I'l happy point all the relevant resources at your new repo once you're happy its generating all the packages people need.

**Comment by hickey** [comment]
@aanon4 I am not sure what the main concern is about transferring the repo if it s not going to be maintained any longer. My primary concern is really keeping the issue history intact and continuing the discussions that is going on in the issues. A bit of searching and GitHub will transfer issues to another repo. I am fine with just transferring the issues if that is acceptable to you. 

As for the new repo, that is not a problem. I have been generating packages for a couple months now and I will just merge my `reorg` branch into `master`. I was looking for a code review, but if there is not going to be any further involvement that is not really going to happen.

**Comment by aanon4** [comment]
I looked at your repo but didnt see any obvious packages I could download and try :-(

**Comment by hickey** [comment]
That is because they are build artifacts in the pipelines at this point since there have not been any releases. 

Here is the latest pipeline that has run from the last MR. https://github.com/hickey/meshchat/actions/runs/6265299153
