### ISSUE TITLE
MeshChat Sessions Not Seeing Eachother. 

### ISSUE THREAD

**Issue by SNosko5** [kn6plv/meshchat#26]
I have multiple MikroTik hAP ac lite APs.  All have the same version of meshchat.  I named all of them MeshChat-1941 according to instructions I found.  I have connectivity between the APs but the individual meshchat sessions don’t seem to be seeing eachother.  I don’t see anyone in Mesh Chat Users.

**Comment by SNosko5** [comment]
I checked Status and see nothing.  I'm new to this so forgive me.

**Comment by hickey** [comment]
Welcome. No problem, we have all started somewhere :-) 

Couple quick questions to insure that we are all on the same page. What version of MeshChat did you install? I just want to make sure that we are addressing the correct version of MeshChat. The currently supported versions are the v2.x versions. 

Also, You state that you named "all of them" MeshChat-1941. I making the assumption that you are referring to the service name that MeshChat is being advertised as and not the node names right? 

Ideally, once the services are created (and you are seeing the services on the mesh status page on the nodes right?) they will begin to see each other and syncing between themselves. That is assuming that `meshchatsync` is running. Check any of the nodes that you have installed MeshChat on to see if there is a `meshchatsync`. If you execute the following you should see output similar to this:

```shell
root@WT0F-1:/etc/rc.d# ps | grep mesh
 2662 root      2300 S    {meshchatsync} /usr/bin/lua /usr/local/bin/meshchatsync
24868 root      1308 S    grep mesh
```

You can also look to see if you have the startup script for `meshchatsync`:

```shell
root@WT0F-1:/etc/rc.d# ls -l /etc/rc.d/*mesh*
lrwxrwxrwx    1 root     root            22 Jun 13 17:00 /etc/rc.d/S99meshchatsync -> ../init.d/meshchatsync
root@WT0F-1:/etc/rc.d# ls -l /etc/init.d/*mesh*
-rwxr-xr-x    1 1001     ntp            229 Jun 13 16:57 /etc/init.d/meshchatsync
```

If you have not rebooted the nodes, then you would need to start (and maybe enable) the service. 

```shell
root@WT0F-1:/etc/rc.d# service meshchatsync start
root@WT0F-1:/etc/rc.d# service meshchatsync enable
```
 
But only do this if the service is not running. If you reboot a node and the service does not start, then execute the `enable` command and reboot again to verify the service starts correctly. 

Hope this helps.

**Comment by SNosko5** [comment]
I downloaded and installed version 1.02 based on the file name.  Where do I get the latest version?  How would I replace the old with the new?  Thanks,

 

Steve Nosko

W4SJN

**Comment by hickey** [comment]
Ah that explains it. I made the same mistake when I first loaded MeshChat because of the way that the AREDN services page is written. It tends to direct people to the old Perl based software. Anything after AREDN v3.22.6.0 no longer includes Perl in the firmware. Without Perl installed the v1.02 software will not function. 

I am assuming that you installed the `meshchat_1.02_all.ipk` file through the administration pages. You can go back into the administration pages and use the remove package selection box to select the MeshChat package and uninstall the package. 

Then you want to download the latest v2.8 package. I don't think that KN6PLV has a location for downloading the packages, but development is moving over to my repo and I have been generating the `.ipk` files for all the changes. You can download the v2.8 version with all the latest patches at https://github.com/hickey/meshchat/suites/16427286094/artifacts/938682298. All you will need to is unzip the file to get the `.ipk` file and then upload it just as you did previously. 

That should get your up and running.

**Comment by SNosko5** [comment]
I replaced the meshchat versions on all APs.   I did enable all of the meshchatsync services.   AREDN does need to change their instructions.  Thank you for all of your help.
